# Generated by Django 5.2.7 on 2025-10-16 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('IDTipoPokemon', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Login', models.CharField(max_length=50, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Senha', models.CharField(max_length=128)),
                ('DtInclusao', models.DateTimeField(auto_now_add=True)),
                ('DtAlteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonUsuario',
            fields=[
                ('IDPokemonUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=50)),
                ('Nome', models.CharField(max_length=100)),
                ('ImagemURL', models.URLField(blank=True, max_length=255, null=True)),
                ('GrupoBatalha', models.BooleanField(default=False)),
                ('Favorito', models.BooleanField(default=False)),
                ('IDTipoPokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to='pokedex_app.tipopokemon')),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pokedex_app.usuario')),
            ],
            options={
                'verbose_name': 'Pokémon do Usuário',
                'verbose_name_plural': 'Pokémons dos Usuários',
            },
        ),
    ]
